In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/TANNERU/Downloads/Dataset for coding/imdb_labelled.txt",delimiter = '\t',names = ['Reviews','Status'])

In [3]:
df

Reviews  Status
0    A very, very, very slow-moving, aimless movie ...       0
1    Not sure who was more lost - the flat characte...       0
2    Attempting artiness with black & white and cle...       0
3         Very little music or anything to speak of.         0
4    The best scene in the movie was when Gerardo i...       1
..                                                 ...     ...
743  I just got bored watching Jessice Lange take h...       0
744  Unfortunately, any virtue in this film's produ...       0
745                   In a word, it is embarrassing.         0
746                               Exceptionally bad!         0
747  All in all its an insult to one's intelligence...       0

[748 rows x 2 columns]

In [4]:
df['Reviews'][0]

'A very, very, very slow-moving, aimless movie about a distressed, drifting young man.  '

In [5]:
from collections import Counter
print(Counter(df['Status']))

Counter({1: 386, 0: 362})


In [6]:
df.isnull().sum()

Reviews    0
Status     0
dtype: int64

In [8]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [9]:
docs = df['Reviews']
labels = df['Status']

In [10]:
docs

0      A very, very, very slow-moving, aimless movie ...
1      Not sure who was more lost - the flat characte...
2      Attempting artiness with black & white and cle...
3           Very little music or anything to speak of.  
4      The best scene in the movie was when Gerardo i...
                             ...                        
743    I just got bored watching Jessice Lange take h...
744    Unfortunately, any virtue in this film's produ...
745                     In a word, it is embarrassing.  
746                                 Exceptionally bad!  
747    All in all its an insult to one's intelligence...
Name: Reviews, Length: 748, dtype: object

In [11]:
labels

0      0
1      0
2      0
3      0
4      1
      ..
743    0
744    0
745    0
746    0
747    0
Name: Status, Length: 748, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest = train_test_split(docs,labels,test_size = 0.3,random_state = 42)

In [47]:
print(Xtrain.shape)
print(Xtest.shape)
print(Ytrain.shape)
print(Ytest.shape)


(523,)
(225,)
(523,)
(225,)


In [48]:
vocab_size = 500 

# The one_hot function expects the following arguments:

In [49]:
Xtrain = [one_hot(d,vocab_size,filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~',lower = True,split = ' ')for d in Xtrain]
Xtest = [one_hot(d,vocab_size,filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~',lower = True,split = ' ')for d in Xtest]

In [50]:
Xtrain

[[296,
  73,
  273,
  204,
  406,
  383,
  216,
  119,
  168,
  452,
  95,
  268,
  216,
  330,
  241,
  276,
  20,
  259,
  82],
 [296,
  289,
  376,
  261,
  337,
  20,
  299,
  150,
  20,
  20,
  442,
  467,
  218,
  59,
  271,
  108,
  280,
  201,
  392,
  48,
  20,
  296,
  387,
  485,
  336,
  448,
  105,
  367,
  296,
  381,
  208,
  11,
  296,
  265,
  229,
  200,
  180,
  168,
  491,
  253,
  220,
  317],
 [168,
  322,
  121,
  63,
  48,
  334,
  442,
  3,
  207,
  18,
  3,
  445,
  146,
  296,
  195,
  394,
  289,
  396,
  242,
  3,
  455,
  134,
  20,
  9],
 [18,
  296,
  449,
  202,
  296,
  263,
  48,
  287,
  172,
  124,
  296,
  94,
  452,
  296,
  93,
  371,
  48,
  403,
  240,
  499,
  103,
  10,
  448,
  150,
  93,
  455,
  430,
  378,
  204,
  296,
  176,
  492,
  48,
  296,
  479,
  174,
  244,
  371,
  448,
  420,
  403,
  56,
  406,
  296,
  140],
 [3, 122, 11, 38, 182],
 [296,
  431,
  202,
  104,
  48,
  38,
  124,
  296,
  218,
  477,
  260,
  17,
  198,
  406,

In [51]:
Xtest

[[296, 371, 371, 48, 289, 448, 319, 137, 460, 273],
 [460,
  48,
  481,
  253,
  464,
  395,
  111,
  119,
  374,
  48,
  321,
  330,
  48,
  364,
  406,
  48,
  139,
  119,
  150],
 [18,
  389,
  177,
  448,
  296,
  93,
  99,
  253,
  242,
  48,
  296,
  129,
  71,
  272,
  28,
  20,
  258,
  476],
 [356, 42, 267, 355, 371, 108, 20, 296, 467],
 [3, 394, 150, 244, 115, 242, 48, 392],
 [371, 168, 423, 20, 48, 93, 253, 235, 50, 345, 177, 150],
 [18, 296, 93, 117, 48, 372, 452, 382, 152],
 [3, 284, 444, 150, 171, 499, 48, 267, 7, 499, 3, 452],
 [328, 328, 328],
 [403, 63, 484],
 [3, 410, 357, 119, 448],
 [235, 152, 143, 377, 206, 452, 398, 48, 271, 428, 105, 52],
 [452, 11, 296, 218, 371, 427],
 [66, 50, 296, 406, 150, 368, 142, 28, 455, 494, 330, 48, 158, 336],
 [280, 499, 439, 183, 389, 80, 63, 296, 336],
 [296, 78, 155, 400, 141, 12, 410],
 [3, 137, 166, 140, 17, 386, 205],
 [296, 218, 455, 471, 246, 375, 275, 345, 177, 48, 498, 344, 138, 93],
 [296,
  129,
  452,
  452,
  304,
  28,


# Pad_sequence

In [52]:
max_length = 25
Xtrain = pad_sequences(Xtrain,maxlen = max_length,padding = 'pre')
Xtest = pad_sequences(Xtest,maxlen = max_length,padding = 'pre')

In [53]:
Xtrain[7],Xtest[7]

(array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 499,
        140, 464, 168, 140,  96, 153, 319, 193, 168, 330, 296, 348]),
 array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          3, 284, 444, 150, 171, 499,  48, 267,   7, 499,   3, 452]))

# Creating Model

In [54]:
from keras.layers import Dropout

In [55]:
model = Sequential()
model.add(Embedding(vocab_size,8,input_length = max_length))
model.add(Dropout(0.3))
model.add(Flatten())
model.add(Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['acc'])

In [56]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 25, 8)             4000      
_________________________________________________________________
dropout_3 (Dropout)          (None, 25, 8)             0         
_________________________________________________________________
flatten_5 (Flatten)          (None, 200)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 201       
Total params: 4,201
Trainable params: 4,201
Non-trainable params: 0
_________________________________________________________________


In [57]:
model.fit(Xtrain,Ytrain,epochs = 20,verbose = 0)

In [58]:
#short form 
#model.fit(Xtrain,Ytrain,validation_data=(Xtest,Ytest),epochs=20,batch_size = 64)

# Training

In [59]:
loss,accuracy= model.evaluate(Xtrain,Ytrain,verbose = 1)
print('Loss : ',loss)
print("Accuracy : ",accuracy)

523/523 [==============================] - 0s 299us/step
Loss :  0.45254585636961303
Accuracy :  0.9254302108948819


# Testing

In [60]:
loss1,accuracy1 = model.evaluate(Xtest,Ytest,verbose = 1)
print('Loss : ',loss1)
print("Accuracy : ",accuracy1)

225/225 [==============================] - 0s 35us/step
Loss :  0.6767256773842706
Accuracy :  0.5733333333333334


In [42]:
predict = model.predict(Xtest)
print(predict)

[[0.5698402 ]
 [0.6135631 ]
 [0.49850696]
 [0.4293198 ]
 [0.5315358 ]
 [0.37467146]
 [0.43080598]
 [0.64581317]
 [0.3845486 ]
 [0.5643125 ]
 [0.41061687]
 [0.56629807]
 [0.46753883]
 [0.51040536]
 [0.47227505]
 [0.56223774]
 [0.45824832]
 [0.395524  ]
 [0.50360703]
 [0.38124496]
 [0.42747727]
 [0.47953495]
 [0.66578805]
 [0.46745035]
 [0.45703375]
 [0.50772727]
 [0.6392613 ]
 [0.6552493 ]
 [0.4672176 ]
 [0.33623296]
 [0.62204283]
 [0.43275094]
 [0.66137403]
 [0.48938215]
 [0.31459856]
 [0.60957223]
 [0.40303946]
 [0.47590214]
 [0.6692246 ]
 [0.32948527]
 [0.62888646]
 [0.5448205 ]
 [0.46378148]
 [0.39720458]
 [0.52978736]
 [0.44553077]
 [0.5745837 ]
 [0.3897587 ]
 [0.5403301 ]
 [0.5506349 ]
 [0.49736872]
 [0.6317614 ]
 [0.5691548 ]
 [0.46388668]
 [0.54735464]
 [0.64615655]
 [0.5896933 ]
 [0.52325237]
 [0.36450166]
 [0.58828974]
 [0.50062025]
 [0.71367127]
 [0.5926036 ]
 [0.5999326 ]
 [0.35521775]
 [0.30784482]
 [0.5109281 ]
 [0.4228642 ]
 [0.5337286 ]
 [0.46951494]
 [0.69906616]
 [0.52

In [43]:
Ypred = np.round(predict) 
print(Ypred)

[[1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.

In [44]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Ytest,Ypred))

[[47 49]
 [29 62]]


In [45]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Ytest,Ypred))

0.5828877005347594
